# docker-compose.yml
version: "3"

services:
  client:
    image: node:15
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 5001:5001
    command: sh -c "yarn install && yarn start"